version: '3.1'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "300:300"
      - "7070:7070"
    volumes:
      - D:\www:/www
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - mysql

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3310:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 7070:7070
  #   environment:
  #     - PMA_HOST=mysql
  #     - PMA_PORT=3310
  #   links:
  #     - mysql
